# Generated by Django 5.0.4 on 2024-04-09 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ChatUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=1000)),
                ('room_name', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2024, 4, 9, 17, 34, 32, 604010))),
                ('message', models.CharField(max_length=100000)),
            ],
        ),
    ]
