# Generated by Django 5.0.4 on 2024-04-09 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web_chat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=1000)),
                ('room_name', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2024, 4, 9, 19, 1, 24, 319776))),
                ('message', models.CharField(max_length=100000)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatUsers',
        ),
    ]
