# Generated by Django 5.0.4 on 2024-04-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web_chat_app', '0002_usermessage_delete_chatusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='date_time',
            field=models.CharField(default='05:17 PM 12-April-2024', max_length=1000),
        ),
    ]
