# Generated by Django 5.0.4 on 2024-04-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web_chat_app', '0003_alter_usermessage_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='date_time',
            field=models.CharField(default='12:04 AM 21-Apr-24', max_length=1000),
        ),
    ]
