# Generated by Django 5.0.4 on 2024-04-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web_chat_app', '0004_alter_usermessage_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='date_time',
            field=models.CharField(default='10:23 AM 26-Apr-24', max_length=1000),
        ),
    ]
