# Generated by Django 4.2.5 on 2024-05-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_time',
            field=models.CharField(default='10:06 PM 05-May-24', max_length=1000),
        ),
    ]
