# Generated by Django 4.2.11 on 2024-05-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0003_alter_message_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_time',
            field=models.CharField(default='03:42 PM 06-May-24', max_length=1000),
        ),
    ]
